# Generated by Django 2.1.6 on 2019-08-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='название')),
                ('address', models.TextField(blank=True, verbose_name='адрес')),
                ('phones', models.CharField(blank=True, max_length=255, verbose_name='телефоны')),
            ],
        ),
    ]
