# Generated by Django 2.1.6 on 2019-08-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='название')),
                ('producing_country', models.CharField(max_length=255, verbose_name='страна производитель')),
                ('vendor_code', models.PositiveIntegerField(default=0, max_length=8, verbose_name='артикул')),
            ],
        ),
    ]
