# Generated by Django 2.1.6 on 2019-08-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.PositiveIntegerField(default=0, verbose_name='артикул'),
        ),
    ]
