# Generated by Django 2.1.6 on 2019-08-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20190813_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='артикул'),
        ),
    ]
