# Generated by Django 2.1.6 on 2019-08-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='useful_volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='полезный объём'),
            preserve_default=False,
        ),
    ]
