# Generated by Django 2.1.6 on 2019-08-13 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0003_auto_20190813_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommingInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=0, max_length=5, verbose_name='номер')),
                ('stockid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_product', to='mainapp.Stock', verbose_name='склад')),
            ],
        ),
        migrations.CreateModel(
            name='CommingInvoiceItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='количество')),
                ('invoiceid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_item', to='stockapp.CommingInvoice', verbose_name='документ')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pruduct_invoice', to='mainapp.Product', verbose_name='товар')),
            ],
        ),
    ]
