# Generated by Django 2.1.6 on 2019-08-14 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_provider'),
        ('stockapp', '0002_auto_20190813_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='comminginvoice',
            name='providerid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='provider_product', to='mainapp.Provider', verbose_name='поставщик'),
            preserve_default=False,
        ),
    ]
